name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB: myFirstApiRestDb
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin123

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Ejecutar pruebas
      run: |
        py manage.py test