name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_HOST: localhost
          POSTGRES_DB: myFirstApiRestDb
          POSTGRES_USER: postgre
          POSTGRES_PASSWORD: admin123

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Ejecutar pruebas
      run: |
        coverage run manage.py test

    - name: Generar informe de cobertura xml 
      run: |
        coverage xml 

    - name: Enviar reporte
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.xml

